[world]
name = "Realms Claim"
description = "A Merkle Drop claim system for cross-chain token distribution using Ethereum signatures and Starknet."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/dojoengine/realms-claim"
seed = "realms_claim"

[world.socials]
x = "https://x.com/ohayo_dojo"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/dojoengine/realms-claim"
telegram = "https://t.me/dojoengine"

[namespace]
default = "realms_claim"

[env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
# Grant write permissions to claim system only
# The forwarder contract exists at 0x50a858cf7abee543a5709f789a0b01482bfe940d65bb12aa13fabf65e048a26
"realms_claim-claim_actions" = ["Campaign", "Claim", "Balance"]
