[package]
name = "merkle_drop"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[scripts]
test = "snforge test"

[dependencies]
starknet = "2.12.0"

openzeppelin_account = "2.0.0"
openzeppelin_access = "2.0.0"
openzeppelin_introspection = "2.0.0"
openzeppelin_merkle_tree = "2.0.0"
openzeppelin_upgrades = "2.0.0"
openzeppelin_security = "2.0.0"
openzeppelin_utils = "2.0.0"

alexandria_bytes = "0.6.0"


[dev-dependencies]
snforge_std = "0.48.1"
assert_macros = "2.12.0"


[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[profile.dev.cairo]
unstable-add-statements-code-locations-debug-info = true
unstable-add-statements-functions-debug-info = true

[[target.starknet-contract]]
sierra = true
casm = true

